SCREEN_WIDTH = 720
SCREEN_HEIGHT = 1280

COLOR_BG = "#0A0A0A"
COLOR_SURFACE = "#111111"
COLOR_CARD = "#1C1B1B"
COLOR_BORDER = "#2A2A2A"
COLOR_BORDER_SOFT = "#222222"

COLOR_PRIMARY = "#FF6600"
COLOR_PRIMARY_PRESSED = "#E65C00"

COLOR_SUCCESS = "#2E7D32"
COLOR_SUCCESS_PRESSED = "#256428"

COLOR_BLUE = "#1565C0"

COLOR_TEXT = "#E8E8E8"
COLOR_TEXT_BRIGHT = "#F5F5F5"
COLOR_TEXT_WHITE = "#FFFFFF"
COLOR_MUTED = "#888888"
COLOR_DISABLED_BG = "#333333"
COLOR_DISABLED_TEXT = "#777777"

COLOR_ONLINE = "#00FF41"
COLOR_ERROR = "#FF3B30"

FONT_FAMILY = "'Be Vietnam Pro', Arial, sans-serif"

FONT_HEADER_TITLE = 28
FONT_PAGE_TITLE = 32
FONT_CARD_TITLE = 32
FONT_CARD_SUBTITLE = 20
FONT_BUTTON = 30
FONT_AMOUNT = 80
FONT_HINT = 18
FONT_FOOTER = 12

HEADER_HEIGHT = 96
HEADER_HEIGHT_COMPACT = 80
BACK_BUTTON_SIZE = 88
BUTTON_HEIGHT = 116
BUTTON_RADIUS = 24
CARD_RADIUS = 24
CARD_RADIUS_LARGE = 28
CARD_BORDER_WIDTH = 2
SELECTED_BORDER_WIDTH = 3
PAGE_MARGIN_X = 32
PAGE_MARGIN_X_COMPACT = 24
FOOTER_HEIGHT = 48
BOTTOM_SAFE_SPACING = 68
BOTTOM_ACTION_HEIGHT = 200
BOTTOM_ACTION_PADDING_TOP = 12
BOTTOM_ACTION_PADDING_BOTTOM = 56


def font_css(size: int, weight: int | str = 700) -> str:
    return f"font-family: {FONT_FAMILY};font-size: {size}px;font-weight: {weight};"


def root_style() -> str:
    return f"background-color: {COLOR_BG};"
