import crypto from 'crypto';

const UUID_REGEX =
    /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

const PENDING_UUID_REGEX =
    /^pending-([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$/i;

const PACKED_ID_REGEX = /^(u|p):[A-Za-z0-9_-]+$/;


// 12 hex chars = 48-bit truncated HMAC.
// Gọn hơn 16 ký tự, vẫn đủ ổn cho QR token ngắn hạn.
// Backend vẫn phải kiểm tra rental status, expiresAt, cabinetId, compartmentId.
const SIGNATURE_LENGTH = 12;

type VerifyQrResult = {
    rentalId: string;
};

function getQrSecret(): string {
    const secret = process.env.QR_SECRET;

    if (!secret) {
        throw new Error('QR_SECRET is required');
    }

    return secret;
}

function uuidToBase64Url(uuid: string): string {
    const cleanHex = uuid.replace(/-/g, '');
    return Buffer.from(cleanHex, 'hex').toString('base64url');
}

function base64UrlToUuid(base64: string): string | null {
    const buf = Buffer.from(base64, 'base64url');

    if (buf.length !== 16) {
        return null;
    }

    const hex = buf.toString('hex');

    return [
        hex.slice(0, 8),
        hex.slice(8, 12),
        hex.slice(12, 16),
        hex.slice(16, 20),
        hex.slice(20),
    ].join('-');
}

function packRentalId(rentalId: string): string {
    if (UUID_REGEX.test(rentalId)) {
        return `u:${uuidToBase64Url(rentalId)}`;
    }

    const pendingMatch = rentalId.match(PENDING_UUID_REGEX);

    if (pendingMatch) {
        return `p:${uuidToBase64Url(pendingMatch[1])}`;
    }

    return rentalId;
}

function unpackRentalId(packed: string): string | null {
    if (packed.startsWith('u:')) {
        return base64UrlToUuid(packed.slice(2));
    }

    if (packed.startsWith('p:')) {
        const uuid = base64UrlToUuid(packed.slice(2));
        return uuid ? `pending-${uuid}` : null;
    }

    return packed || null;
}

function signPayload(payload: string): string {
    return crypto
        .createHmac('sha256', getQrSecret())
        .update(payload)
        .digest('hex')
        .substring(0, SIGNATURE_LENGTH);
}

function safeCompareSignature(inputSig: string, expectedSig: string): boolean {
    const inputBuffer = Buffer.from(inputSig);
    const expectedBuffer = Buffer.from(expectedSig);

    if (inputBuffer.length !== expectedBuffer.length) {
        return false;
    }

    return crypto.timingSafeEqual(inputBuffer, expectedBuffer);
}

/**
 * QR token format:
 *
 *   <kind>:<packedId>.<signature>
 *
 * kind:
 *   u = normal rental UUID
 *   p = pending rental UUID
 *
 * Example:
 *   u:VQ6EAOKbQdSnFkRmVUQAAA.a1b2c3d4e5f67890
 *
 * This only verifies that the QR token was generated by backend
 * and was not modified. Business validation must still check:
 * rental exists, status ACTIVE, expiresAt, cabinetId and compartmentId.
 */
export function signQrToken(rentalId: string): string {
    const payload = packRentalId(rentalId);
    const signature = signPayload(payload);

    return `${payload}.${signature}`;
}

export function verifyQrToken(token: string): VerifyQrResult | null {
    try {
        const parts = token.split('.');

        if (parts.length !== 2) {
            return null;
        }

        const [payload, signature] = parts;

        if (!payload || !signature) {
            return null;
        }

        if ((payload.startsWith('u:') || payload.startsWith('p:')) && !PACKED_ID_REGEX.test(payload)) {
            return null;
        }

        const expectedSignature = signPayload(payload);

        if (!safeCompareSignature(signature, expectedSignature)) {
            return null;
        }

        const rentalId = unpackRentalId(payload);

        if (!rentalId) {
            return null;
        }

        return { rentalId };
    } catch {
        return null;
    }
}