ALTER TYPE "CabinetStatus" ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE "CabinetStatus" ADD VALUE IF NOT EXISTS 'PENDING_PROVISION';
ALTER TYPE "CabinetStatus" ADD VALUE IF NOT EXISTS 'PROVISION_FAILED';

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PROVISION_CABINET_SUCCESS';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PROVISION_CABINET_FAILURE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'UPDATE_PROVISIONING_CONFIG';

ALTER TABLE "Cabinet"
  ADD COLUMN IF NOT EXISTS "provisionCode" TEXT,
  ADD COLUMN IF NOT EXISTS "provisionCodeExpires" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "configVersion" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "hardwareSerial" TEXT,
  ADD COLUMN IF NOT EXISTS "notes" TEXT;

ALTER TABLE "Compartment"
  ADD COLUMN IF NOT EXISTS "rowIndex" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "colIndex" INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS "ProvisioningConfig" (
  "id" TEXT NOT NULL,
  "strategy" TEXT NOT NULL DEFAULT 'ENV',
  "provisionKey" TEXT NOT NULL DEFAULT 'smartbox-provision',
  "provisionSecret" TEXT,
  "webhookUrl" TEXT,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ProvisioningConfig_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "Cabinet_provisionCode_key" ON "Cabinet"("provisionCode");
CREATE INDEX IF NOT EXISTS "Cabinet_provisionCode_idx" ON "Cabinet"("provisionCode");
CREATE INDEX IF NOT EXISTS "Cabinet_hardwareSerial_idx" ON "Cabinet"("hardwareSerial");
